packages/scafflater-cli/commands/init.js, packages/scafflater-cli/commands/partial/list.js, packages/scafflater-cli/commands/partial/run.js, packages/scafflater/generator/appenders/region-appender.js, packages/scafflater/generator/appenders/region-appender.test.js, packages/scafflater/generator/index.js, packages/scafflater/generator/index.test.js, packages/scafflater/generator/processors/hbs-builtin-helpers/lineComment.test.js, packages/scafflater/generator/region-provider/index.test.js, packages/scafflater/options-provider/index.js, packages/scafflater/options-provider/index.test.js, packages/scafflater/scafflater.js, packages/scafflater/scafflater.test.js, packages/scafflater/template-cache/index.js, packages/scafflater/template-cache/storages/dir-cache.js, packages/scafflater/template-cache/storages/home-dir-cache.js, packages/scafflater/template-cache/storages/temp-dir-cache.js, packages/scafflater/template-manager/index.test.js, packages/scafflater/template-source/git-template-source.js, packages/scafflater/template-source/index.js, packages/scafflater/util/index.js, packages/scafflater/util/index.test.js
=> Config to options

packages/scafflater/generator/appenders/yaml-appender.js, packages/scafflater/generator/appenders/yaml-appender.test.js
=> Fixing array merge

.vscode/settings.json, package-lock.json, packages/scafflater-cli/commands/init.js, packages/scafflater-cli/commands/init.test.js, packages/scafflater/errors/TemplateInitialized.js, packages/scafflater/errors/index.js, packages/scafflater/index.js, packages/scafflater/scafflater-config/config.js, packages/scafflater/scafflater-config/config.test.js, packages/scafflater/scafflater.js, packages/scafflater/scafflater.test.js
=> Throw specific error if template is initialized

packages/scafflater/generator/index.js, packages/scafflater/generator/index.test.js, packages/scafflater/options/index.js
=> Add ignore option to append strategy

.github/workflows/cd.yml, .github/workflows/release.yml, package-lock.json, packages/scafflater/fs-util/index.js, packages/scafflater/package.json
=> Fix Release and fsUtil bug

.github/workflows/release.yml
=> Fix install

.github/workflows/release.yml
=> Force scafflater version install

.github/workflows/release.yml
=> Workflow fix

.github/workflows/release.yml
=> fix install scafflater

packages/scafflater/template-source/git-template-source/git-template-source.js, packages/scafflater/template-source/git-template-source/git-template-source.test.js, packages/scafflater/template-source/github-client-template-source/github-client-template-source.js, packages/scafflater/template-source/github-client-template-source/github-client-template-source.test.js
=> fix regex to validate repos

.vscode/launch.json, .vscode/settings.json
=> Fix jest configuration

packages/scafflater/generator/index.js
=> Read config from directory

packages/scafflater/errors/file-process-error.js, packages/scafflater/errors/index.js, packages/scafflater/generator/index.js, packages/scafflater/template-source/octokit-template-source/octokit-template-source.test.js
=> Include file name on log

packages/scafflater/generator/index.js, packages/scafflater/generator/processors/processor.js
=> Load prettier config from template path

packages/scafflater/generator/index.js
=> Fix config use

packages/scafflater/fs-util/index.js, packages/scafflater/fs-util/index.test.js
=> Fix npm install on template root

packages/scafflater-cli/commands/init.js, packages/scafflater-cli/commands/partial/run.js, packages/scafflater-cli/util/dot-prop.js, packages/scafflater-cli/util/dot-prop.test.js, packages/scafflater-cli/util/index.js, packages/scafflater-cli/util/index.test.js, packages/scafflater/scafflater.test.js
=> Add dot in parameter name

packages/scafflater/template-source/git-template-source/git-template-source.js, packages/scafflater/template-source/git-template-source/git-template-source.test.js
=> Add protectNTFS = false

packages/scafflater/scafflater-config/config.js
=> Fix circular dependency

package-lock.json, packages/scafflater/package.json
Update git url parser to fix vulnerabilities.
=> Update git url parser

package-lock.json, packages/scafflater/generator/appenders/toml-appender.js, packages/scafflater/generator/appenders/toml-appender.test.js, packages/scafflater/package.json
=> TOML Appender

packages/scafflater/fs-util/fs-util.mocking-fs-extra.test.js, packages/scafflater/fs-util/index.js
=> Add prefix to temp dir

packages/scafflater/generator/appenders/json-appender.js, packages/scafflater/generator/appenders/json-appender.test.js, packages/scafflater/generator/appenders/toml-appender.js, packages/scafflater/generator/appenders/toml-appender.test.js, packages/scafflater/generator/appenders/yaml-appender.js, packages/scafflater/generator/appenders/yaml-appender.test.js
=> Fix empty strings

packages/scafflater/generator/appenders/json-appender.js, packages/scafflater/generator/appenders/json-appender.test.js, packages/scafflater/generator/appenders/toml-appender.js, packages/scafflater/generator/appenders/toml-appender.test.js, packages/scafflater/generator/appenders/yaml-appender.js, packages/scafflater/generator/appenders/yaml-appender.test.js
=> Fix empty objects with comments

packages/scafflater/generator/appenders/json-appender.js, packages/scafflater/generator/appenders/json-appender.test.js
=> String Json Comments

package-lock.json, packages/scafflater/package.json, packages/scafflater/scafflater-config/config.js, packages/scafflater/scafflater-config/local-template.js, packages/scafflater/scafflater-config/partial-config.js, packages/scafflater/scafflater-config/template-config.js, packages/scafflater/scafflater.js, packages/scafflater/template-source/octokit-template-source/octokit-template-source.test.js, packages/scafflater/util/run-command.js, packages/scafflater/util/run-command.test.js
Add pre and post script for templates and partials
=> Add pre and post scripts

packages/scafflater/generator/appenders/toml-appender.js, packages/scafflater/generator/appenders/toml-appender.test.js
Fix toml appender for multiline properties.
=> Fix toml-appender for multi-line properties

packages/scafflater/scafflater.js, packages/scafflater/util/run-command.test.js
Signed-off-by: Francisco.Ribas <chico_bribas@hotmail.com>
=> Fix runCommand wrong parameter

package-lock.json, packages/scafflater/generator/index.js, packages/scafflater/generator/index.test.js, packages/scafflater/options/index.js, packages/scafflater/package.json
Enable globs to select targets where results should be appended.
=> Add glob patterns for targetName

packages/scafflater/generator/index.js, packages/scafflater/generator/index.test.js
Enable to use handlebars on glob target names
=> feat: add handlebars support for glob target name

.gitignore, package-lock.json, package.json, packages/scafflater-cli/package.json, packages/scafflater/fixup, packages/scafflater/package.json, packages/scafflater/template-source/isomorphic-git-template-source/isomorphic-git-template-source.js, packages/scafflater/tsconfig-cjs.json, packages/scafflater/tsconfig-esm.json, packages/scafflater/tsconfig.json
Most off clients are not ready for pure ESM packages. Downgrade pure packages that are pure ESM to be compatible with those clients.
=> fix: remove pure ESM packages

package.json, packages/scafflater-cli/commands/partial/run.js, packages/scafflater-cli/commands/partial/run.test.js
Fix to receive both partial and template as parameters.
=> fix: Receive both partial and template as parameter
